USE ROLE SYSADMIN;

CREATE WAREHOUSE  WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

USE WAREHOUSE ;

CREATE DATABASE ;

USE DATABASE ;

CREATE SCHEMA ;

USE ROLE SECURITYADMIN;
CREATE ROLE ;

GRANT USAGE ON WAREHOUSE  TO ROLE ;

GRANT USAGE ON DATABASE  TO ROLE ;

USE ROLE SYSADMIN;
USE WAREHOUSE ;
USE DATABASE ;

GRANT USAGE ON SCHEMA  TO ROLE ;

GRANT CREATE TABLE ON SCHEMA  TO ROLE ;

GRANT CREATE STAGE ON SCHEMA  TO ROLE ;

GRANT CREATE PIPE ON SCHEMA  TO ROLE ;

USE ROLE SECURITYADMIN;

CREATE USER 
  PASSWORD = ''
  DEFAULT_WAREHOUSE = ''
  DEFAULT_NAMESPACE = '.'
  RSA_PUBLIC_KEY = ''
  DEFAULT_ROLE = '';
  
GRANT ROLE  TO USER ;
