#!/bin/bash

# Read configuration file
source ../config.txt

# Read the RSA public key from the RSA_PUBLIC_KEY.txt file
SNOWFLAKE_PUBLIC_KEY=$(cat ../RSA_PUBLIC_KEY.txt | grep RSA_PUBLIC_KEY | cut -d "=" -f2)

# Generate SQL script
cat > create_user.sql <<EOF
USE ROLE SYSADMIN;

CREATE WAREHOUSE $WAREHOUSE_NAME WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

USE WAREHOUSE $WAREHOUSE_NAME;

CREATE DATABASE $DATABASE_NAME;

USE DATABASE $DATABASE_NAME;

CREATE SCHEMA $SCHEMA_NAME;

USE ROLE SECURITYADMIN;
CREATE ROLE $ROLE_NAME;

GRANT USAGE ON WAREHOUSE $WAREHOUSE_NAME TO ROLE $ROLE_NAME;

GRANT USAGE ON DATABASE $DATABASE_NAME TO ROLE $ROLE_NAME;

USE ROLE SYSADMIN;
USE WAREHOUSE $WAREHOUSE_NAME;
USE DATABASE $DATABASE_NAME;

GRANT USAGE ON SCHEMA $SCHEMA_NAME TO ROLE $ROLE_NAME;

GRANT CREATE TABLE ON SCHEMA $SCHEMA_NAME TO ROLE $ROLE_NAME;

GRANT CREATE STAGE ON SCHEMA $SCHEMA_NAME TO ROLE $ROLE_NAME;

GRANT CREATE PIPE ON SCHEMA $SCHEMA_NAME TO ROLE $ROLE_NAME;

USE ROLE SECURITYADMIN;

CREATE USER $USER_NAME
  PASSWORD = '$PASSPHRASE'
  DEFAULT_WAREHOUSE = '$WAREHOUSE_NAME'
  DEFAULT_NAMESPACE = '$DATABASE_NAME.$SCHEMA_NAME'
  RSA_PUBLIC_KEY = '$SNOWFLAKE_PUBLIC_KEY'
  DEFAULT_ROLE = '$ROLE_NAME';
  
GRANT ROLE $ROLE_NAME TO USER $USER_NAME;
EOF
