USE ROLE SYSADMIN;

CREATE WAREHOUSE KAFKA_CONNECT_1 WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

USE WAREHOUSE KAFKA_CONNECT_1;

CREATE DATABASE ORDERS_DB_1;

USE DATABASE ORDERS_DB_1;

CREATE SCHEMA ORDERS_SCHEMA_1;

USE ROLE SECURITYADMIN;
CREATE ROLE KAFKA_CONNECT_1_ORDERS_ROLE;

GRANT USAGE ON WAREHOUSE KAFKA_CONNECT_1 TO ROLE KAFKA_CONNECT_1_ORDERS_ROLE;

GRANT USAGE ON DATABASE ORDERS_DB_1 TO ROLE KAFKA_CONNECT_1_ORDERS_ROLE;

USE ROLE SYSADMIN;
USE WAREHOUSE KAFKA_CONNECT_1;
USE DATABASE ORDERS_DB_1;

GRANT USAGE ON SCHEMA ORDERS_SCHEMA_1 TO ROLE KAFKA_CONNECT_1_ORDERS_ROLE;

GRANT CREATE TABLE ON SCHEMA ORDERS_SCHEMA_1 TO ROLE KAFKA_CONNECT_1_ORDERS_ROLE;

GRANT CREATE STAGE ON SCHEMA ORDERS_SCHEMA_1 TO ROLE KAFKA_CONNECT_1_ORDERS_ROLE;

GRANT CREATE PIPE ON SCHEMA ORDERS_SCHEMA_1 TO ROLE KAFKA_CONNECT_1_ORDERS_ROLE;

USE ROLE SECURITYADMIN;

CREATE USER ORDERS_CONNECT_USER_1
  PASSWORD = 'Develop3r'
  DEFAULT_WAREHOUSE = 'KAFKA_CONNECT_1'
  DEFAULT_NAMESPACE = 'ORDERS_DB_1.ORDERS_SCHEMA_1'
  RSA_PUBLIC_KEY = ' "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqf3UeN/08qVdsOI4V6lU25hJI0Ke0HZBAfRmBy5nkMOg4U2J+EwHepePzKzali3nmUU2Vo1GdD9NfmhXZYjeUlebEfQdPOUPNksJw+sSR3Vljk/PRFaOnTAR2mtpyBwPWD/h6ZNILTUhs7OpC7AUSsW4m7JhhW47IF1Tv+HXpzGpzOHN1OLQ6wofmNlnJXeNvpezdRSmK/rk1W08fXPOOJXhp59efAl/jI2S2gPQMB7Z4ELGENJm57hGWtaf9s9+E0OhOJJpSQJbvpFbU3UtL0Y/2XmpHc2SKdSbVUUreuz3BCmsnWwt7DmRve8gs0hw4mv5I+tjkMeyjMhMgTGNawIDAQAB"'
  DEFAULT_ROLE = 'KAFKA_CONNECT_1_ORDERS_ROLE';
  
GRANT ROLE KAFKA_CONNECT_1_ORDERS_ROLE TO USER ORDERS_CONNECT_USER_1;
